export const typeDefs = `
    type Blog {
        id: ID! @autogenerated
        name: String!
        creator: User @relationship(type: "HAS_BLOG", direction: "IN")
        authors: [User] @relationship(type: "CAN_POST", direction: "IN")
    }
`;
