import gql from "graphql-tag";

export const typeDefs = gql`
    type Blog @timestamps {
        id: ID! @autogenerated
        name: String!
        creator: User @relationship(type: "HAS_BLOG", direction: "IN")
        authors: [User] @relationship(type: "CAN_POST", direction: "IN")
        posts: [Post] @relationship(type: "HAS_POST", direction: "OUT")
        isCreator: Boolean # TODO
        isAuthor: Boolean # TODO
    }

    extend type Blog
        @auth(
            rules: [
                { operations: ["create"], bind: { creator: { id: "sub" } } }
                { operations: ["read"], allow: "*" }
                {
                    operations: ["update"]
                    bind: {
                        OR: [{ creator: { id: "sub" }, authors: { id: "sub" } }]
                    }
                    allow: {
                        OR: [
                            { creator: { id: "sub" } }
                            { authors: { id: "sub" } }
                        ]
                    }
                }
                { operations: ["delete"], allow: { creator: { id: "sub" } } }
            ]
        )
`;
