import gql from "graphql-tag";

export const typeDefs = gql`
    type Comment @timestamps {
        id: ID! @autogenerated
        author: User @relationship(type: "COMMENTED", direction: "IN")
        content: String!
        post: Post @relationship(type: "HAS_COMMENT", direction: "IN")
    }
`;
