import gql from "graphql-tag";

export const typeDefs = gql`
    type Post @timestamps {
        id: ID! @autogenerated
        title: String!
        content: String!
        blog: Blog @relationship(type: "HAS_POST", direction: "IN")
        comments: [Comment] @relationship(type: "HAS_COMMENT", direction: "OUT")
        author: User @relationship(type: "WROTE", direction: "IN")
        canEdit: Boolean
            @cypher(
                statement: """
                OPTIONAL MATCH (this)<-[:WROTE]-(author:User {id: $jwt.sub})
                OPTIONAL MATCH (this)<-[:HAS_POST]-(blog:Blog)
                OPTIONAL MATCH (blog)<-[:HAS_BLOG]-(blogCreator:User {id: $jwt.sub})
                OPTIONAL MATCH (blog)<-[:CAN_POST]-(blogAuthors:User {id: $jwt.sub})
                WITH (
                    (author IS NOT NULL) OR
                    (blogCreator IS NOT NULL) OR
                    (blogAuthors IS NOT NULL)
                ) AS canEdit
                RETURN canEdit
                """
            )
        canDelete: Boolean
            @cypher(
                statement: """
                OPTIONAL MATCH (this)<-[:WROTE]-(author:User {id: $jwt.sub})
                OPTIONAL MATCH (this)<-[:HAS_POST]-(blog:Blog)
                OPTIONAL MATCH (blog)<-[:HAS_BLOG]-(blogCreator:User {id: $jwt.sub})
                WITH (
                    (author IS NOT NULL) OR
                    (blogCreator IS NOT NULL)
                ) AS canDelete
                RETURN canDelete
                """
            )
    }

    extend type Post
        @auth(
            rules: [
                { operations: ["create"], bind: { author: { id: "sub" } } }
                { operations: ["read"], allow: "*" }
                {
                    operations: ["update"]
                    allow: {
                        OR: [
                            { author: { id: "sub" } }
                            {
                                blog: {
                                    OR: [
                                        { creator: { id: "sub" } }
                                        { authors: { id: "sub" } }
                                    ]
                                }
                            }
                        ]
                    }
                }
                {
                    operations: ["delete"]
                    allow: {
                        OR: [
                            { author: { id: "sub" } }
                            { blog: { creator: { id: "sub" } } }
                        ]
                    }
                }
            ]
        )
`;
