import gql from "graphql-tag";

export const typeDefs = gql`
    type Post @timestamps {
        id: ID! @autogenerated
        title: String!
        content: String!
        blog: Blog @relationship(type: "HAS_POST", direction: "IN")
        comments: [Comment] @relationship(type: "HAS_COMMENT", direction: "OUT")
        author: User @relationship(type: "WROTE", direction: "IN")
    }
`;
